/**
 * Plug tuning (Ideas2 §2; design/11 §2; Prompt 26 centralizes). The plug intro
 * COSTS live on the country roster (`config/countries.ts` `plugCost` /
 * `plugPriceFactor` — per-source data); the scalar here is the shared meeting
 * overhead. v1 balance HYPOTHESES held as config, never scattered literals
 * (prompts/README.md "Config, not literals").
 */

/** Heat generated by taking the intro meeting (shown before commit — fairness). */
export const PLUG_MEETING_HEAT = 5;
